// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './i18n-formatters'
import type { Locales, Translations } from './i18n-types.generated'
import { loadedFormatters, loadedLocales, locales } from './i18n-util.generated'

import en from './en'

import en_app from './en/app'
import en_common from './en/common'
import en_config from './en/config'
import en_home from './en/home'
import en_models from './en/models'
import en_sources from './en/sources'
import en_tasks from './en/tasks'

const localeTranslations = {
	en: {
		...en,
		app: en_app,
		common: en_common,
		config: en_config,
		home: en_home,
		models: en_models,
		sources: en_sources,
		tasks: en_tasks
	},
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
