// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './i18n-formatters'
import type { Locales, Translations } from './i18n-types.generated'
import { loadedFormatters, loadedLocales, locales } from './i18n-util.generated'

import en from './en'

import en_common from './en/common'
import en_config from './en/config'

const localeTranslations = {
	en: {
		...en,
		common: en_common,
		config: en_config
	},
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
