// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	app: NamespaceAppTranslation,
	common: NamespaceCommonTranslation,
	config: NamespaceConfigTranslation,
	home: NamespaceHomeTranslation,
	models: NamespaceModelsTranslation,
	sources: NamespaceSourcesTranslation,
	tasks: NamespaceTasksTranslation
}

type RootTranslation = {
	/**
	 * S​T​L​ ​O​r​g​a​n​i​z​e​r
	 */
	title: string
}

export type NamespaceAppTranslation = {
	navigation: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * M​o​d​e​l​s
		 */
		models: string
		/**
		 * S​o​u​r​c​e​s
		 */
		sources: string
		/**
		 * T​a​s​k​s
		 */
		tasks: string
		/**
		 * C​o​n​f​i​g
		 */
		config: string
	}
}

export type NamespaceCommonTranslation = {
	actions: {
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * S​a​v​e
		 */
		save: string
	}
}

export type NamespaceConfigTranslation = {
	/**
	 * C​o​n​f​i​g
	 */
	pageTitle: string
	errors: {
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​c​o​n​f​i​g
		 */
		failedUpdate: string
	}
	form: {
		fields: {
			outputFolder: {
				/**
				 * O​u​t​p​u​t​ ​f​o​l​d​e​r
				 */
				label: string
			}
			tempFolder: {
				/**
				 * T​e​m​p​ ​F​o​l​d​e​r
				 */
				label: string
			}
			maxThreads: {
				/**
				 * M​a​x​ ​T​h​r​e​a​d​s
				 */
				label: string
			}
			autoProcessOnScan: {
				/**
				 * A​u​t​o​ ​P​r​o​c​e​s​s​ ​o​n​ ​S​c​a​n
				 */
				label: string
			}
			autoArchiveOnComplete: {
				/**
				 * A​u​t​o​ ​A​r​c​h​i​v​e​ ​o​n​ ​C​o​m​p​l​e​t​e
				 */
				label: string
			}
			useMultithreading: {
				/**
				 * U​s​e​ ​M​u​l​t​i​t​h​r​e​a​d​i​n​g
				 */
				label: string
			}
			debugMode: {
				/**
				 * D​e​b​u​g​ ​M​o​d​e
				 */
				label: string
			}
		}
	}
}

export type NamespaceHomeTranslation = {
	/**
	 * H​o​m​e
	 */
	pageTitle: string
}

export type NamespaceModelsTranslation = {
	/**
	 * M​o​d​e​l​s
	 */
	pageTitle: string
}

export type NamespaceSourcesTranslation = {
	/**
	 * S​o​u​r​c​e​s
	 */
	pageTitle: string
}

export type NamespaceTasksTranslation = {
	/**
	 * T​a​s​k​s
	 */
	pageTitle: string
}

export type Namespaces =
	| 'app'
	| 'common'
	| 'config'
	| 'home'
	| 'models'
	| 'sources'
	| 'tasks'

type DisallowNamespaces = {
	/**
	 * reserved for 'app'-namespace\
	 * you need to use the `./app/index.ts` file instead
	 */
	app?: "[typesafe-i18n] reserved for 'app'-namespace. You need to use the `./app/index.ts` file instead."

	/**
	 * reserved for 'common'-namespace\
	 * you need to use the `./common/index.ts` file instead
	 */
	common?: "[typesafe-i18n] reserved for 'common'-namespace. You need to use the `./common/index.ts` file instead."

	/**
	 * reserved for 'config'-namespace\
	 * you need to use the `./config/index.ts` file instead
	 */
	config?: "[typesafe-i18n] reserved for 'config'-namespace. You need to use the `./config/index.ts` file instead."

	/**
	 * reserved for 'home'-namespace\
	 * you need to use the `./home/index.ts` file instead
	 */
	home?: "[typesafe-i18n] reserved for 'home'-namespace. You need to use the `./home/index.ts` file instead."

	/**
	 * reserved for 'models'-namespace\
	 * you need to use the `./models/index.ts` file instead
	 */
	models?: "[typesafe-i18n] reserved for 'models'-namespace. You need to use the `./models/index.ts` file instead."

	/**
	 * reserved for 'sources'-namespace\
	 * you need to use the `./sources/index.ts` file instead
	 */
	sources?: "[typesafe-i18n] reserved for 'sources'-namespace. You need to use the `./sources/index.ts` file instead."

	/**
	 * reserved for 'tasks'-namespace\
	 * you need to use the `./tasks/index.ts` file instead
	 */
	tasks?: "[typesafe-i18n] reserved for 'tasks'-namespace. You need to use the `./tasks/index.ts` file instead."
}

export type TranslationFunctions = {
	/**
	 * STL Organizer
	 */
	title: () => LocalizedString
	app: {
		navigation: {
			/**
			 * Home
			 */
			home: () => LocalizedString
			/**
			 * Models
			 */
			models: () => LocalizedString
			/**
			 * Sources
			 */
			sources: () => LocalizedString
			/**
			 * Tasks
			 */
			tasks: () => LocalizedString
			/**
			 * Config
			 */
			config: () => LocalizedString
		}
	}
	common: {
		actions: {
			/**
			 * Cancel
			 */
			cancel: () => LocalizedString
			/**
			 * Save
			 */
			save: () => LocalizedString
		}
	}
	config: {
		/**
		 * Config
		 */
		pageTitle: () => LocalizedString
		errors: {
			/**
			 * Failed to update config
			 */
			failedUpdate: () => LocalizedString
		}
		form: {
			fields: {
				outputFolder: {
					/**
					 * Output folder
					 */
					label: () => LocalizedString
				}
				tempFolder: {
					/**
					 * Temp Folder
					 */
					label: () => LocalizedString
				}
				maxThreads: {
					/**
					 * Max Threads
					 */
					label: () => LocalizedString
				}
				autoProcessOnScan: {
					/**
					 * Auto Process on Scan
					 */
					label: () => LocalizedString
				}
				autoArchiveOnComplete: {
					/**
					 * Auto Archive on Complete
					 */
					label: () => LocalizedString
				}
				useMultithreading: {
					/**
					 * Use Multithreading
					 */
					label: () => LocalizedString
				}
				debugMode: {
					/**
					 * Debug Mode
					 */
					label: () => LocalizedString
				}
			}
		}
	}
	home: {
		/**
		 * Home
		 */
		pageTitle: () => LocalizedString
	}
	models: {
		/**
		 * Models
		 */
		pageTitle: () => LocalizedString
	}
	sources: {
		/**
		 * Sources
		 */
		pageTitle: () => LocalizedString
	}
	tasks: {
		/**
		 * Tasks
		 */
		pageTitle: () => LocalizedString
	}
}

export type Formatters = {}
